// <auto-generated />
using System;
using HuffmanFileCompressor.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HuffmanFileCompressor.App.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250530194321_Add extension to model")]
    partial class Addextensiontomodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("HuffmanFileCompressor.App.Model.Archives", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompressedSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("Extension")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OriginalSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Archives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompressedSize = 100,
                            Created = new DateTime(2025, 5, 27, 15, 10, 45, 0, DateTimeKind.Unspecified),
                            Extension = 0,
                            Modified = new DateTime(2025, 5, 27, 15, 10, 45, 0, DateTimeKind.Unspecified),
                            Name = "Archive 1 file",
                            OriginalSize = 100,
                            Path = "Archive 1 file"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
